config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "gossips#index"
  resources :moussaillons

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :moussailon
end

app/models/moussaillon.rb
class Moussaillon < ApplicationRecord
  has_many :gossips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bidon_controller.rb
class BidonController < ApplicationController
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
    @gossips = Gossip.all?
  end

  def new
    @gossip = Gossip.new
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def create
    @gossip = Gossip.new(params_gossip)
    if @gossip.save
      redirect_to gossip_path(@moussaillon)
    else
      redirect_to new_gossip_path
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(params_gossip)
  end


  private
    def params_gossip
      params.require(:gossip).permit(:body, :moussaillon)
    end
end

app/controllers/moussaillons_controller.rb
class MoussaillonsController < ApplicationController

  def new
    @moussaillon = Moussaillon.new
  end

  def show
    @moussaillon = Moussaillon.find(params[:id])
  end

  def index
    @moussaillons = Moussaillon.all
  end


  def create
    @moussaillon = Moussaillon.new(params_moussaillon)
    if @moussaillon.save
      redirect_to moussaillon_path(@moussaillon)
    else
      redirect_to new_moussaillon_path
    end
  end

  def edit
    @moussaillon = Moussaillon.find(params[:id])
  end

  def update
    @moussaillon = Moussaillon.find(params[:id])

    if @moussaillon.update(mou)
      redirect_to @moussaillon
    else
      render 'edit'
    end
  end


  private

  def params_moussaillon
    params.require(:moussaillon).permit(:username,:email,:bio)
  end
end

app/controllers/moussaillons_controller2.rb
class MoussailonsController < ApplicationController

  def new
    @moussaillon = Moussaillon.new
  end

  def show
    @moussaillon = Moussaillon.find(params[:id])
  end

  def index
    @moussaillons = Moussaillon.all
  end


  def create
    @moussaillon = Moussaillon.new(params_moussaillon)
    if @moussaillon.save
      link_to moussaillon_path(@moussaillon)
    else
      link_to new_moussaillon_path
    end
  end

  def edit
    @moussaillon = Moussaillon.find(params[:id])
  end

  def update
    @moussaillon = Moussaillon.find(params[:id])

    if @moussaillon.update(article_params)
      redirect_to @moussaillon
    else
      render 'edit'
    end
  end


  private

  def params_moussaillon
    params.require(:moussaillon).permit(:username,:email,:bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bidon_helper.rb
module BidonHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/moussaillons_helper.rb
module MoussaillonsHelper
end

app/helpers/moussailons_helper.rb
module MoussailonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>S4J4</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/moussaillons/edit.html.erb
<h1> Modifier un moussaillon </h1>

<%= form_for @moussaillon do |m| %>

  <%= m.label :username %>:
  <%= m.text_field :username, placeholder: "Username" %><br />


  <%= m.label :email %>:
  <%= m.text_field :email, placeholder: "Email" %><br />

  <%= m.label :bio %>:
  <%= m.text_field :bio, placeholder: "Bio" %><br />

  <%= m.submit %>
<% end %>

  <%= link_to "Supprimer", moussaillon_path(@moussaillon), method: "DELETE" %>

app/views/moussaillons/index.html.erb
<h1> Liste des moussaillons </h1>

<% @moussaillons.each do |m| %>

<p> Username : <%= m.username %>, Email : <%= m.email %> ,
  <%= link_to "Sa page", moussaillon_path(m) %> </p>

<% end %>

app/views/moussaillons/new.html.erb
<h1> Nouveau moussaillon ! </h1>

<%= form_for @moussaillon do |m| %>


  <%= m.label :username %>:
  <%= m.text_field :username, placeholder: "Username" %><br />


  <%= m.label :email %>:
  <%= m.text_field :email, placeholder: "Email" %><br />

  <%= m.submit "Créer ici" %>

<% end %>

app/views/moussaillons/show.html.erb
<h1> Afficher le moussaillon </h1>

<%= form_for @moussaillon do |m| %>

  <%= m.label :username %>:
  <%= m.text_field :username %><br />


  <%= m.label :email %>:
  <%= m.text_field :email %><br />


  <%= link_to "Modifier", edit_moussaillon_path(@moussaillon) %>

<% end %>